services:
  web:
    configs:
      - source: app_env
        target: /app/.env
    image: my-flask-app:1.0.0
    build: .
    ports:
      - "5005:8000"
    develop:
      watch:
        - path: ./requirements.txt
          action: rebuild
        - path: .env
          action: restart
        - path: .
          target: /app
          action: sync
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=myapp
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
configs:
  app_env:
    file: ./.env