sonar.projectKey=flask-restful-udemy
sonar.projectName=Flask REST API

sonar.sources=.
sonar.tests=tests

sonar.exclusions=tests/**,.venv/**,venv/**,code/**,reports/**,**/__pycache__/**

sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.sourceEncoding=UTF-8